### ISSUE TITLE
Designing AsyncAPI 

### ISSUE THREAD

**Issue by naveenkumaran** [Apicurio/apicurito#134]
@EricWittmann we are planning to integrate the editor in our home grown API explorer. Can u please tell me if apicurito can be used to design AsyncAPI. If so please point me to the document where we can enable this feature 

Sorry this is not an issue, but I couldn't find a better place to ask this query.

**Comment by EricWittmann** [comment]
Hi @naveenkumaran - thanks for the question.  Apicurito doesn't currently support AsyncAPI.  Our AsyncAPI editor is currently in beta (in progress) and not enabled by default even in Apicurio Studio.

Could you please open a GH issue in the apicurio-studio repository to request the AsyncAPI editor as a standalone editor component?  That's the way Apicurito works today - it embeds this component:

https://www.npmjs.com/package/apicurio-design-studio

I'll have to check (it's been awhile) but I think that component is only the OpenAPI editor.  We may need to introduce something new so that the AsyncAPI editor is consumable in the way Apicurito (and your home grown API explorer) can use it.

Of course, we'd be very happy to get a contribution on this. :) :)

**Comment by naveenkumaran** [comment]
Thank you @EricWittmann.

I have opened a new issue [here](https://github.com/Apicurio/apicurio-studio/issues/1633). 

I will be happy to contribute when I find some time :)

**Comment by EricWittmann** [comment]
Awesome thanks!  If you need some pointers to get you started let me know.
