### ISSUE TITLE
Store unsaved content in browser local storage in case the user accidentally closes the browser

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurito#2]
It would be nice to have a way for the user to recover their work if they accidentally close the browser window.

**Comment by Cediddi** [comment]
I think keeping a json dump in local storage would be the easiest fix. I wish I could do angularjs. I think a simple "save session" button with adjustable "auto-save" timer would be great, alongside a "load session". But you'll need to name sessions, otherwise someone might think that it does and save on top of the previous session.

**Comment by EricWittmann** [comment]
Thanks for the feedback, @Cediddi .

By the way, this GitHub project (`apicurito`) is a stateless version (a "lite" version, if you will) of the full Apicurio Studio application.  This version doesn't have any server components, collaboration, Dashboard, API list, etc... but is instead a simple standalone version of the API editor found in Apicurio Studio.

So if you're using e.g. https://studio.apicur.io - then you are using the full app, which has a different GitHub repository found here:  https://github.com/Apicurio/apicurio-studio

I'm guessing you're not actually using Apicurito (this repo) - but if you are then that's OK too (probably you're using a docker image to run it).

**Comment by Cediddi** [comment]
I tried using apicurio locally on docker-compose but failed miserably and found out this beauty and it works wonderfully on docker. I'm using apicurito because I don't need collaborative features. Sometimes browsers do crash and I understand apicurito is stateless but auto-save feature would be great to have.

The reason I suggested local storage as a auto-save space is because the app still can be stateless and save me from a possible crash. Other possibility of auto-save, downloading json, wouldn't be as nice as local storage because of download file dialogs constantly popping up every few minutes or so.

I'm using apicurito since monday and finding some small bugs along the way. (eg. generate button shows an empty list, you can't rename properties of data types in design window, can't load a yaml file) and I really want to help this application to be perfect but I lack the experience in angularjs, I'm more of a python and backend guy.

It's truly a joy to use, 10/10.

**Comment by EricWittmann** [comment]
Oh wow - that's great!  I'm happy you found Apicurito and it's useful for you.

Any issues you find or improvements you would like to see, please raise them!  Even though you aren't an angular developer, just providing your feedback as a user is very helpful.  

If possible, please raise any issues you find with the editor itself in the `apicurio-studio` repository - otherwise they won't get the attention they deserve. :)

As for **this** issue - I'll bump the priority of it since it's not very hard to implement.  We might have to start out with just a single session and graduate to named sessions in a future update. :)

**Comment by Cediddi** [comment]
That is godlike! Thank you Eric :heart:

**Comment by EricWittmann** [comment]
I've added disaster recovery to Apicurito - changes are saved periodically in local storage so in case the browser is closed or crashes, work can be recovered.  @Cediddi if you'd like to open a new GH ticket for enhancing this support with multiple editing sessions, please feel free.  :)
