### ISSUE TITLE
operation TRACE is not reflected in json/yaml

### ISSUE THREAD

**Issue by mmajerni** [Apicurio/apicurito#42]
- Create path and operations GET and TRACE

json/yaml should looks like:
```
paths:
    /testPath:
        get: {}
        trace: {}

```
but it looks like:
```
paths:
    /testPath:
        get: {}

```

Operation TRACE is not reflected in json/yaml. So export API does not export TRACE operation.

**Comment by EricWittmann** [comment]
Are you creating/editing an OpenAPI 2 document or an OpenAPI 3 document?

**Comment by EricWittmann** [comment]
I suspect you're editing an OpenAPI 2 document, because the **trace** operation is not supported in that version of the spec (it was introduced in OpenAPI 3).  There seems to be a bug in Apicurio where the **TRACE** operation is visible in OpenAPI 2 docs by mistake.  So it's allowing you to create/edit that operation but it won't be written out because it's not part of the spec.

**Comment by mmajerni** [comment]
I am using latest **apicurio/apicurito-ui** image which was built:
Built On | Apr 1, 2019
and yes, it uses OpenAPI 2 (by default): **swagger: '2.0'**

**Comment by EricWittmann** [comment]
Oh yes - I didn't even realize that this was reported in the **apicurito** repository, which definitely means that you're using OpenAPI 2 (since Apicurito doesn't allow anything else).  OK - the bug here is definitely that the TRACE option is even visible in the UI for 2.0 docs.  I'll get that taken care of.

**Comment by EricWittmann** [comment]
This was fixed! :)
